### ISSUE TITLE
Decide what release model will look like

### ISSUE THREAD

**Issue by GodloveD** [sylabs/singularity-cri#180]
Singularity has a [certain release model](https://www.sylabs.io/2018/03/managing-singularity-branches/) that might work well for singularity-cri too.  But there may be tweaks to this model that would serve singularity-cri well, or there may be a whole other model that will work better.  It's almost time to create a first release, so now would be a good time to figure out what the release model should look like!

**Comment by sashayakovtseva** [comment]
Looks like it is same as `Release Branch Model` from [here](https://www.renemoser.net/blog/2016/01/09/release-strategies/), which I find to be the most suitable release strategy for singularity-cri.
