### ISSUE TITLE
seccomp not found during build process

### ISSUE THREAD

**Issue by coneheadusa** [sylabs/singularity-cri#225]
After running make dep && make lint successfully, I get the following error during the build process on my CentOS Linux release 7.6.1810 (Core)  system with libseccomp-devel.x86_64             2.3.1-3.el7 installed.  PKG_CONFIG_PATH is set to /usr/lib/pkgconfig where the libseccomp.pc is installed.   Please provide guidance as to how I might resolve the issue.

$ make
 GO bin/sycri
 WARNING: seccomp is not found, ignoring
# github.com/seccomp/libseccomp-golang
../../../../pkg/mod/github.com/seccomp/libseccomp-golang@v0.9.0/seccomp_internal.go:23:2: error: #error Minimum supported version of Libseccomp is v2.1.0
 #error Minimum supported version of Libseccomp is v2.1.0
  ^
make: *** [bin/sycri] Error 2

**Comment by sashayakovtseva** [comment]
Hello @coneheadusa! 
When installing Singularity, did you see line like `checking: libseccomp+headers... yes` during `./mconfig` run?

**Comment by sashayakovtseva** [comment]
Also just in case, is `gcc` installed?

**Comment by sashayakovtseva** [comment]
Hey @coneheadusa, it looks like there was a broken check for seccomp in Makefile, PR #228 should fix that. Thank you for bringing that up!

**Comment by sashayakovtseva** [comment]
If you still facing this error, feel free to reopen this issue

**Comment by coneheadusa** [comment]
Thank you for the quick reply.  I’ll test on my system.
