### ISSUE TITLE
Could not run buildcfg

### ISSUE THREAD

**Issue by coneheadusa** [sylabs/singularity-cri#241]
I've searched the issues listed here  and various singularity documents and I am unable to determine why I  get the following messages when I execute  sycri.   What am I missing?

sycri
#####################################################################
0328 15:10:50.359779   53541 network.go:112] Network configuration found: flannel
I0328 15:10:50.360154   53541 main.go:175] Singularity CRI server started on /var/run/singularity.sock
E0328 15:10:50.377733   53541 main.go:100] Could not start Singularity device plugin: could not create Singularity device plugin: could not get build config: could not run buildcfg command: exit status 1
I0328 15:10:50.377800   53541 main.go:178] Singularity CRI service exiting...
#####################################################################

singularity --version
singularity version 3.1.0

The singularity.conf and sycri.yaml files are attached as one file.
[singularity.txt](https://github.com/sylabs/singularity-cri/files/3020355/singularity.txt)

**Comment by sashayakovtseva** [comment]
Hello @coneheadusa! Can you confirm that `singularity buildcfg` is successfully run on your host?

**Comment by sashayakovtseva** [comment]
If not, please, try to checkout `v.3.1.1-rc1` tag in Singularity repo itself

**Comment by coneheadusa** [comment]
buildcfg did not exist in my current version of singularity.  I checked out v3.1.1-rc1 and it looks like the seccomp issue has returned.

$ make
 GO singularity
    [+] GO_TAGS "containers_image_openpgp apparmor selinux seccomp"
# github.com/sylabs/singularity/vendor/github.com/seccomp/libseccomp-golang
../vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go:23:2: error: #error Minimum supported version of Libseccomp is v2.1.0
 #error Minimum supported version of Libseccomp is v2.1.0
  ^
make: *** [singularity] Error 2

**Comment by sashayakovtseva** [comment]
Did you run `./mconfig` before `make` after checking out `v3.1.1-rc1` in Singularity? Looks like issue may appear due to invalid libseccomp installation so that it is not found during build.

**Comment by coneheadusa** [comment]
I've attached a file that lists all the commands I used to try to build singularity with v3.1.1-rc1.  The ./mconfig was included in the set. 
[singularitybuild-v3.1.1-rc1.txt](https://github.com/sylabs/singularity-cri/files/3034881/singularitybuild-v3.1.1-rc1.txt)

**Comment by cclerget** [comment]
Hi @coneheadusa , to help us to figure out what happens please provide output of:

- `grep SCMP_VER_MAJOR /usr/include`
- `pkg-config --cflags --libs libseccomp`

And be sure you installed system dependencies like described at https://github.com/sylabs/singularity/blob/master/INSTALL.md for Centos/RHEL and also try the following compilation steps :

```
git clean -xfd
go clean -cache
./mconfig
make -C builddir
sudo make -C builddir install
```

**Comment by coneheadusa** [comment]
I believe you can close this issue.  For what it's worth here is some background. 
Singularity 3.1.0 built on the system prior to checking out v3.1.1-rc1 about a week ago.   The problems began when I tried to build v3.1.1-rc1.  During the ' find  /usr/include -type f -exec grep SCMP_VER_MAJOR {} \;'  command you suggested, the system crashed as a result of a disk failure.   I rebuilt both singularity and singularity-cri on a different system without any problems.  I assume the make process was having difficulty reading /usr/include directory on the original hardware thus causing the errors.   At any rate, I'm back on track.  Thank you for your help.

**Comment by cclerget** [comment]
Oh very bad side effect :/, but finally solved. Closing
