### ISSUE TITLE
Migrate to k8s.io/cri-api for CRI

### ISSUE THREAD

**Issue by sashayakovtseva** [sylabs/singularity-cri#249]
K8s has moved CRI into a separate repo recently, do we want to update CRI accordingly?  Not much benefit, just keeping us aligned.

**Comment by GodloveD** [comment]
Are you asking if we should move singularity-cri to a separate repo too?  Separate from what?  It's already in it's own repo.  I'm sure I'm missing something silly.

**Comment by sashayakovtseva** [comment]
@GodloveD I am asking if we should reference new CRI (k8s.io/cri-api) in dependencies

**Comment by GodloveD** [comment]
Oh that makes sense.

**Comment by sashayakovtseva** [comment]
My bad, looks like we'll need to update k8s itself as well to ≥ v.1.15.0-alpha.1
I suggest closing this issue and think about migrating after some time.
