### ISSUE TITLE
Migrate to using SCS supported library (and other) clients

### ISSUE THREAD

**Issue by GodloveD** [sylabs/singularity-cri#251]
Use this instead:

https://github.com/sylabs/scs-library-client

**Comment by sashayakovtseva** [comment]
Oops, that repo is private and in CRI we vendor deps. Do we want to make repo public or vendor private code a bit? Maybe @tri-adam will help

**Comment by tri-adam** [comment]
The official SCS Library client will be open-sourced shortly (sylabs/scs-library-client#11).
