### ISSUE TITLE
Remove GO111MODULES environment variable from Makefile

### ISSUE THREAD

**Issue by jscook2345** [sylabs/singularity-cri#280]
I would leave setting this environment variable up to the user pre-build and just document it as a part of the install process. This also means you could set the minimum version of go to be `1.12` as well.

What do you think?

**Comment by sashayakovtseva** [comment]
This variable is set only during particular command execution to leverage vendor directory. 
The only reason switching to `mod=vendor` is to be aligned with Singularity repo, otherwise effect is the same. 
@mem any differences between `GO111MODULE` and `mod=vendor` during build process?
