### ISSUE TITLE
Make sure to use the goflag -mod=vendor

### ISSUE THREAD

**Issue by jscook2345** [sylabs/singularity-cri#281]
Since we're using a vendor directory for building the product, we should make sure to use the `-mod=vendor` flag so that vendor dependencies are not downloaded to the user's `GOPATH`.

@mem did some of this work for `singularity` and perhaps could comment more here.

**Comment by sashayakovtseva** [comment]
GO111MODULE=off makes it use vendor

**Comment by jscook2345** [comment]
@sashayakovtseva 

I checked the build and this is true with go1.11 if you build under `$GOPATH/src`. How do you build with go1.11 under any path and use the `vendor` directory? Do you want to support that build option? (Not supporting it would be OK. We could go straight to requiring go1.12, which would have cleaner build instructions).

**Comment by sashayakovtseva** [comment]
Yes, I want to support that, reopening to check and possibly fix
