### ISSUE TITLE
Move golangci-lint config to a configuration file

### ISSUE THREAD

**Issue by jscook2345** [sylabs/singularity-cri#285]
Some parts of the configuration for the tool cannot be done with command-line options and requires using a config file.

**Comment by jscook2345** [comment]
I'd be happy to do this if you give it a 👍 @sashayakovtseva Let me know what you think!

**Comment by sashayakovtseva** [comment]
Maybe we should use config file and switch to https://golangci.com/ for linting?
Also can you explain why we need `modules-download-mode` set? To check dependencies?
